with open("patches/xenos_recomp_fixes.patch", "w") as f:
    f.write('diff --git a/XenosRecomp/CMakeLists.txt b/XenosRecomp/CMakeLists.txt\n')
    f.write('index e505a5e..0574517 100644\n')
    f.write('--- a/XenosRecomp/CMakeLists.txt\n')
    f.write('+++ b/XenosRecomp/CMakeLists.txt\n')
    f.write('@@ -28,7 +28,7 @@ target_include_directories(XenosRecomp PRIVATE )\n')
    f.write(' \n')
    f.write(' target_precompile_headers(XenosRecomp PRIVATE pch.h)\n')
    f.write(' \n')
    f.write('-if (CMAKE_CXX_COMPILER_ID STREQUAL "Clang" OR CMAKE_CXX_COMPILER_ID STREQUAL "AppleClang")\n')
    f.write('+if (CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang" OR CMAKE_CXX_COMPILER_ID STREQUAL "AppleClang")\n')
    f.write('     target_compile_options(XenosRecomp PRIVATE -Wno-switch -Wno-unused-variable -Wno-null-arithmetic -fms-extensions)\n')
    f.write(' \n')
    f.write('     include(CheckCXXSymbolExists)\n')
    f.write('diff --git a/XenosRecomp/shader_recompiler.cpp b/XenosRecomp/shader_recompiler.cpp\n')
    f.write('index 698a418..79c02f1 100644\n')
    f.write('--- a/XenosRecomp/shader_recompiler.cpp\n')
    f.write('+++ b/XenosRecomp/shader_recompiler.cpp\n')

    # Hunk 1 (1308) - Empty blank line
    f.write('@@ -1308,15 +1308,15 @@ void ShaderRecompiler::recompile(const uint8_t* shaderData, const std::string_vi\n')
    f.write('             {\n')
    f.write('                 VertexElement vertexElement;\n')
    f.write('                 uint32_t value;\n')
    f.write('-            };\n')
    f.write('+            } u;\n')
    f.write(' \n')
    f.write('-            value = vertexShader->vertexElementsAndInterpolators[vertexShader->field18 + i];\n')
    f.write('+            u.value = vertexShader->vertexElementsAndInterpolators[vertexShader->field18 + i];\n')
    f.write(' \n')
    f.write('-            const char* usageType = USAGE_TYPES[uint32_t(vertexElement.usage)];\n')
    f.write('+            const char* usageType = USAGE_TYPES[uint32_t(u.vertexElement.usage)];\n')
    f.write(' \n')
    f.write('         #ifdef UNLEASHED_RECOMP\n')
    f.write('-            if ((vertexElement.usage == DeclUsage::TexCoord && vertexElement.usageIndex == 2 && isMetaInstancer) ||\n')
    f.write('-                (vertexElement.usage == DeclUsage::Position && vertexElement.usageIndex == 1))\n')
    f.write('+            if ((u.vertexElement.usage == DeclUsage::TexCoord && u.vertexElement.usageIndex == 2 && isMetaInstancer) ||\n')
    f.write('+                (u.vertexElement.usage == DeclUsage::Position && u.vertexElement.usageIndex == 1))\n')
    f.write('             {\n')
    f.write('                 usageType = "uint4";\n')
    f.write('             }\n')
    f.write('@@ -1326,17 +1326,17 @@ void ShaderRecompiler::recompile(const uint8_t* shaderData, const std::string_vi\n')
    f.write(' \n')
    f.write('             for (auto& usageLocation : USAGE_LOCATIONS)\n')
    f.write('             {\n')
    f.write('-                if (usageLocation.usage == vertexElement.usage && usageLocation.usageIndex == vertexElement.usageIndex)\n')
    f.write('+                if (usageLocation.usage == u.vertexElement.usage && usageLocation.usageIndex == u.vertexElement.usageIndex)\n')
    f.write('                 {\n')
    f.write('                     print("[[vk::location({})]] ", usageLocation.location);\n')
    f.write('                     break;\n')
    f.write('                 }\n')
    f.write('             }\n')
    f.write(' \n')
    f.write('-            println("in {0} i{1}{2} : {3}{2},", usageType, USAGE_VARIABLES[uint32_t(vertexElement.usage)],\n')
    f.write('-                uint32_t(vertexElement.usageIndex), USAGE_SEMANTICS[uint32_t(vertexElement.usage)]);\n')
    f.write('+            println("in {0} i{1}{2} : {3}{2},", usageType, USAGE_VARIABLES[uint32_t(u.vertexElement.usage)],\n')
    f.write('+                uint32_t(u.vertexElement.usageIndex), USAGE_SEMANTICS[uint32_t(u.vertexElement.usage)]);\n')
    f.write(' \n')
    f.write('-            vertexElements.emplace(uint32_t(vertexElement.address), vertexElement);\n')
    f.write('+            vertexElements.emplace(uint32_t(u.vertexElement.address), u.vertexElement);\n')
    f.write('         }\n')
    f.write(' \n')
    f.write('     #ifdef UNLEASHED_RECOMP\n')

    # Hunk 2 (1403) - Empty blank line
    f.write('@@ -1403,13 +1403,13 @@ void ShaderRecompiler::recompile(const uint8_t* shaderData, const std::string_vi\n')
    f.write('                         int8_t y;\n')
    f.write('                         int8_t z;\n')
    f.write('                         int8_t w;\n')
    f.write('-                    };\n')
    f.write('+                    } s;\n')
    f.write('                 };\n')
    f.write(' \n')
    f.write('                 value = definition->values[i].get();\n')
    f.write(' \n')
    f.write('                 println("\tint4 i{} = int4({}, {}, {}, {});",\n')
    f.write('-                    (definition->registerIndex - 8992) / 4 + i, x, y, z, w);\n')
    f.write('+                    (definition->registerIndex - 8992) / 4 + i, s.x, s.y, s.z, s.w);\n')
    f.write('             }\n')
    f.write('             definitions += 2;\n')
    f.write('             definitions += definition->count;\n')

    # Hunk 3 (1502) - Empty blank line, 9 lines
    f.write('@@ -1502,9 +1502,9 @@ void ShaderRecompiler::recompile(const uint8_t* shaderData, const std::string_vi\n')
    f.write('             uint32_t code1;\n')
    f.write('             uint32_t code2;\n')
    f.write('             uint32_t code3;\n')
    f.write('-        };\n')
    f.write('+        } codes;\n')
    f.write('     };\n')
    f.write(' \n')
    f.write('     auto controlFlowCode = code;\n')
    f.write('     uint32_t instrAddress = 0;\n')
    f.write('     uint32_t instrSize = shader->size;\n')

    # Hunk 4 (1512)
    f.write('@@ -1512,10 +1512,10 @@ void ShaderRecompiler::recompile(const uint8_t* shaderData, const std::string_vi\n')
    f.write(' \n')
    f.write('     while (instrAddress < instrSize)\n')
    f.write('     {\n')
    f.write('-        code0 = controlFlowCode[0];\n')
    f.write('-        code1 = controlFlowCode[1] & 0xFFFF;\n')
    f.write('-        code2 = (controlFlowCode[1] >> 16) | (controlFlowCode[2] << 16);\n')
    f.write('-        code3 = controlFlowCode[2] >> 16;\n')
    f.write('+        codes.code0 = controlFlowCode[0];\n')
    f.write('+        codes.code1 = controlFlowCode[1] & 0xFFFF;\n')
    f.write('+        codes.code2 = (controlFlowCode[1] >> 16) | (controlFlowCode[2] << 16);\n')
    f.write('+        codes.code3 = controlFlowCode[2] >> 16;\n')
    f.write(' \n')
    f.write('         for (auto& cfInstr : controlFlow)\n')
    f.write('         {\n')

    # Hunk 4b (1579)
    f.write('@@ -1579,10 +1579,10 @@ void ShaderRecompiler::recompile(const uint8_t* shaderData, const std::string_vi\n')
    f.write(' \n')
    f.write('     while (instrAddress < instrSize)\n')
    f.write('     {\n')
    f.write('-        code0 = controlFlowCode[0];\n')
    f.write('-        code1 = controlFlowCode[1] & 0xFFFF;\n')
    f.write('-        code2 = (controlFlowCode[1] >> 16) | (controlFlowCode[2] << 16);\n')
    f.write('-        code3 = controlFlowCode[2] >> 16;\n')
    f.write('+        codes.code0 = controlFlowCode[0];\n')
    f.write('+        codes.code1 = controlFlowCode[1] & 0xFFFF;\n')
    f.write('+        codes.code2 = (controlFlowCode[1] >> 16) | (controlFlowCode[2] << 16);\n')
    f.write('+        codes.code3 = controlFlowCode[2] >> 16;\n')
    f.write(' \n')
    f.write('         for (auto& cfInstr : controlFlow)\n')
    f.write('         {\n')

    # Hunk 5 (1733) - Blank line with 12 spaces
    f.write('@@ -1733,12 +1733,12 @@ void ShaderRecompiler::recompile(const uint8_t* shaderData, const std::string_vi\n')
    f.write('                         uint32_t code0;\n')
    f.write('                         uint32_t code1;\n')
    f.write('                         uint32_t code2;\n')
    f.write('-                    };\n')
    f.write('+                    } raw;\n')
    f.write('                 };\n')
    # 1 space context marker + 12 spaces indentation
    f.write(' ' + ' ' * 12 + '\n')
    f.write('-                code0 = instructionCode[0];\n')
    f.write('-                code1 = instructionCode[1];\n')
    f.write('-                code2 = instructionCode[2];\n')
    f.write('+                raw.code0 = instructionCode[0];\n')
    f.write('+                raw.code1 = instructionCode[1];\n')
    f.write('+                raw.code2 = instructionCode[2];\n')
    f.write(' \n')
    f.write('                 if ((sequence & 0x1) != 0)\n')
    f.write('                 {\n')
