if (NOT ANDROID)
    add_subdirectory(${UNLEASHED_RECOMP_TOOLS_ROOT}/bc_diff)
    add_subdirectory(${UNLEASHED_RECOMP_TOOLS_ROOT}/file_to_c)
    add_subdirectory(${UNLEASHED_RECOMP_TOOLS_ROOT}/fshasher)
    add_subdirectory(${UNLEASHED_RECOMP_TOOLS_ROOT}/x_decompress)
endif()
add_subdirectory(${UNLEASHED_RECOMP_TOOLS_ROOT}/XenonRecomp)
add_subdirectory(${UNLEASHED_RECOMP_TOOLS_ROOT}/XenosRecomp)
